name: "package"

on:
  workflow_dispatch:
  push:
    branches:
      - "master"

jobs:
  package:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-2019]
        include:
        - os: ubuntu-latest
          cc: musl-gcc
          cflags: -O2 -flto -fno-plt
          pkgext: .tar.xz
        - os: macos-latest
          cc: clang
          cflags: -O2 -flto -fno-plt
          pkgext: .tar.xz
        - os: windows-2019
          cc: gcc
          cflags: -O2 -m32
          pkgext: .zip
    runs-on: ${{matrix.os}}
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 0
    - name: Install musl
      if: ${{ matrix.os == 'ubuntu-latest' }}
      run: sudo apt-get update && sudo apt-get install musl-tools

    - name: Remove MinGW 64 completely
      if: ${{ matrix.os == 'windows-2019' }}
      run: rm -rf C:\ProgramData\chocolatey\lib\mingw\tools\install\mingw64
      
    - name: Set up MinGW
      if: ${{ matrix.os == 'windows-2019' }}
      uses: egor-tensin/setup-mingw@v2
      with:
        platform: x32
        version: 12.2.0
    - name: Package
      shell: bash
      run: make package CC=${{matrix.cc}} CFLAGS="${{matrix.cflags}}"
    - name: Adjust variables
      shell: bash
      id: pkgvars
      run: |
        pkgfile=`ls pkg/*${{matrix.pkgext}}`
        echo "::set-output name=pkgfile::$pkgfile";
    - name: Upload pre release
      uses: ncipollo/release-action@v1
      with:
        name: Latest Nelua in development
        tag: latest
        artifacts: ${{steps.pkgvars.outputs.pkgfile}}
        token: ${{secrets.GITHUB_TOKEN}}
        prerelease: true
        allowUpdates: true
        body:
          Precompiled Nelua binary package rebuilt at every new commit in master branch.
